/**
* @author: Muhammad Raza
* @description: This Class representing denormalized information about a session.
* @since: 01/01/24
* @Last Modified by: Muhammad Raza
*/
public with sharing class DenormalizedSession {

    @AuraEnabled 
	public String sessionId;
    @AuraEnabled 
	public String sessionName;
    @AuraEnabled 
	public String sessionTitle;
    @AuraEnabled 
	public String sessionDescription;
    @AuraEnabled    
	public Date sessionStartDate;
    @AuraEnabled
	public Date sessionEndDate;
    @AuraEnabled
	public String sessionStartTime;
    @AuraEnabled
	public String sessionEndTime;
    @AuraEnabled
	public String sessionDuration;
    @AuraEnabled
	public String sessionTrack;
    @AuraEnabled
	public List<DenormalizedSpeaker> lstOfSpeakers;




    @AuraEnabled public String speakerName;
    @AuraEnabled public String speakerPhone;
    @AuraEnabled public String speakerRole;
    @AuraEnabled public String speakerTarget;
    @AuraEnabled public String speakerEmail;
    @AuraEnabled public String companyName;
    @AuraEnabled public String speakerInformation;
    @AuraEnabled public String speakerSocialMedia;

    @AuraEnabled public String coSpeakerName;
    @AuraEnabled public String coSpeakerCompanyName;
    @AuraEnabled public String coSpeakerPhone;
    @AuraEnabled public String coSpeakerEmail;
    @AuraEnabled public String coSpeakerTitle;
    @AuraEnabled public String coSpeakerRole;
    @AuraEnabled public String coSpeakerImage;
    @AuraEnabled public String coSpeakerImageBlob;


    public DenormalizedSession(){}


    public void setSessionName(String sessionName){

        this.sessionName = sessionName;
    }
    public void setSessionId(String sessionId){

        this.sessionId = sessionId;
    }
    public void setStartTime(String sessionStartTime){

        this.sessionStartTime = sessionStartTime;
    }
    public void setEndTime(String sessionEndTime){

        this.sessionEndTime = sessionEndTime;
    }
    public void setSessionTitle(String sessionTitle){

        this.sessionTitle = sessionTitle;
    }
    public void setSessionDescription(String sessionDescription){

        this.sessionDescription = sessionDescription;
    }
    public void setSessionTrack(String sessionTrack){

        this.sessionTrack = sessionTrack;
    }


    // -----------speaker-----------------------

    
    public void setSpeakerName(String speakerName){

        this.speakerName = speakerName;
    }
    public void setSpeakerPhone(String speakerPhone){

        this.speakerPhone = speakerPhone;
    }
    public void setSpeakerRole(String speakerRole){

        this.speakerRole = speakerRole;
    }
    public void setSpeakerTarget(String speakerTarget){

        this.speakerTarget = speakerTarget;
    }
    public void setSpeakerEmail(String speakerEmail){

        this.speakerEmail = speakerEmail;
    }
    public void setSpeakerCompanyName(String companyName){

        this.companyName = companyName;
    }
    public void setSpeakerInformation(String speakerInformation){

        this.speakerInformation = speakerInformation;
    }
    public void setSpeakerSocialMedia(String speakerSocialMedia){

        this.speakerSocialMedia = speakerSocialMedia;
    }


   // ----------- co speaker-----------------------


   public void setCoSpeakerName(String coSpeakerName){

    this.coSpeakerName = coSpeakerName;
        }

   public void setCoSpeakerCompanyName(String coSpeakerCompanyName){

    this.coSpeakerCompanyName = coSpeakerCompanyName;
        }
   public void setCoSpeakerPhone(String coSpeakerPhone){

    this.coSpeakerPhone = coSpeakerPhone;
        }
   public void setCoSpeakerEmail(String coSpeakerEmail){

    this.coSpeakerEmail = coSpeakerEmail;
        }
   public void setCoSpeakerTitle(String coSpeakerTitle){

    this.coSpeakerTitle = coSpeakerTitle;
        }
   public void setCoSpeakerRole(String coSpeakerRole){

    this.coSpeakerRole = coSpeakerRole;
        }
   public void setCoSpeakerImage(String coSpeakerImage){

    this.coSpeakerImage = coSpeakerImage;
        }


      
}